version: '3.8'
services:
  zookeeper:
    image: 'confluentinc/cp-zookeeper:7.5.0'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '2181:2181'

  kafka:
    image: 'confluentinc/cp-kafka:7.5.0'
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3 # Update to latest version
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - ELASTIC_PASSWORD=password
      - xpack.security.enabled=true # Enable security features
      - xpack.security.enrollment.enabled=true # Enable enrollment for Kibana
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - ./elasticsearch-init-scripts:/usr/share/elasticsearch/init-scripts # Mount the initialization script

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2 # Optional Kibana for visualization
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_user # Use the new username
      - ELASTICSEARCH_PASSWORD=password # Use the new password
      - xpack.encryptedSavedObjects.encryptionKey=123456789012345678901234567890aa # Set the persistent encryption key
    depends_on:
      - elasticsearch
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml # Mount the kibana.yml file with the encryption key

volumes:
  es_data:
    driver: local
